version: 2.0

# The goal here is to generate updated(i.e. updates installed) base image every day.
# This requires scheduled workflow
# Currently, just triggers rebuild on Docker hub every day

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Install curl
          command: apk add curl
      - run:
          name: Rebuild on docker hub
          command: sh rebuild-on-docker-hub.sh
          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "10 13 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build